[package]
name = "amfiteatr_proc_macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]

syn = {version = "2.0.48", features = ["full", "fold"]}
quote = "1.0.35"
proc-macro2 = { version =  "1.0.76", features = ["proc-macro"]}
enum-map-derive = "0.17.0"
